Create some components
Romancikh/presentation-maker pull request #3
Opened 2023-10-07 08:28 UTC by 555Jeka555

2023-10-07 13:18 UTC, Romancikh requested changes

2023-10-07 13:18 UTC, roman-kutimskii commented on src/components/PopUpMenu/PopUpMenu.tsx
> +function PopUpMenu() {
Думаю, надо назвать просто Menu

2023-10-07 13:18 UTC, roman-kutimskii commented on src/components/PopUpMenuElement/PopUpMenuElement.tsx
> +function PopUpMenuElement({ leftText, rightText }: popUpMenuElementProps) {
Та же ситуация, просто MenuElement

2023-10-07 13:18 UTC, Romancikh commented on src/components/PopUpMenuElement/PopUpMenuElement.tsx
> +  leftText: string;
Измени на text и shortcut. Также можно убрать null и использовать `shortcut?: string`.

2023-10-07 13:18 UTC, Romancikh commented on src/components/PanelTools/PanelTools.tsx
> +function PanelTools() {
Если я правильно понимаю, это панель инструментов. Лучше просто назвать TollBar. Это название более каноническое.

2023-10-07 13:18 UTC, Romancikh commented on src/components/Header/Header.tsx
> +function Header() {
Header - это нечто большее. Он должен содержать в себе MenuBar и ToolBar.

2023-10-07 13:18 UTC, Romancikh commented on src/components/Header/Header.tsx
> +        <Button text={"Файл"} imagePath={null} imageAlt={null} />
Это надо вынести в отдельный компонент MenuBar.

2023-10-07 13:18 UTC, Romancikh commented on src/components/Button/Button.tsx
> +  imagePath: string | null;
Иконки подключаются через тег `<link>`. Их использование по этой [ссылке](https://developers.google.com/fonts/docs/material_symbols#using_material_symbols). Пример `<span class="material-symbols-outlined">search</span>`. Так что в компонент надо передавать только название иконки, свойство можно назвать просто `icon`. Тут так же используй знак "?" для обозначения необязательного поля.

2023-10-07 13:18 UTC, Romancikh commented on src/components/Button/Button.tsx
> +      )}
Надо поправить. Будет как-то так
```typescript
<>
  <button>
    {icon ?? <span className="material-symbols-outlined">{icon}</span>}
    {text}
  </button>
</>
```

2023-10-07 18:19 UTC, 555Jeka555 commented on src/components/PopUpMenuElement/PopUpMenuElement.tsx
> +  leftText: string;
В php бы выглядело ?string shrotcut. Там знак вопроса перед типом переменной ставится, поэтому и не знал куда его по итогу в TS писать

2023-10-07 20:01 UTC, Romancikh requested changes

2023-10-07 20:01 UTC, roman-kutimskii commented on src/components/Button/Button.tsx
Для select нужен отдельный компонент. Мне текущая реализация не нравится.

2023-10-07 20:01 UTC, roman-kutimskii commented on src/components/SlideBar/SlideBar.tsx
> +        })}
Ты забыл добавить key. Для key надо использовать id. Если у нас большое количество слайдов, мы используем index в качестве ключа и решили удалить первый слайд, у всех слайдов поменяется key, и React обновит все слайды.

2023-10-07 20:01 UTC, roman-kutimskii commented on src/components/SlideBar/SlideBar.tsx
> +type slideBarProps = {
Типы с прописной буквы.

2023-10-07 20:01 UTC, roman-kutimskii commented on src/components/SlidePreview/SlidePreview.tsx
> +type slidePreviewProps = {
Типы с прописной буквы.

2023-10-07 20:01 UTC, roman-kutimskii commented on src/components/SlideBar/SlideBar.tsx
> +        {slides.map((el, ind) => {
Прошу не сокращать. И лучше заменить element на slide, чтобы добавить конкретики.

2023-10-07 20:01 UTC, roman-kutimskii commented on src/components/Header/Header.tsx
>      </>
Думаю, лучше поместить их в div, а не использовать фрагменты.

2023-10-07 20:01 UTC, roman-kutimskii commented on src/components/Menu/Menu.tsx
> +    </>
Так как здесь есть div, фрагменты можно не использовать.

2023-10-07 20:01 UTC, roman-kutimskii commented on src/components/MenuBar/MenuBar.tsx
> +    </>
Надо убрать фрагменты.

2023-10-07 20:01 UTC, roman-kutimskii commented on src/components/MenuElement/MenuElement.tsx
> +    </>
Надо убрать фрагменты.

2023-10-07 20:01 UTC, roman-kutimskii commented on src/components/MenuElement/MenuElement.tsx
> +// eslint-disable-next-line @typescript-eslint/no-unused-vars
Нужно убрать этот комментарий.

2023-10-07 20:01 UTC, roman-kutimskii commented on src/components/ToolBar/ToolBar.tsx
> +    </>
Надо убрать фрагменты

2023-10-07 20:01 UTC, Romancikh commented on src/components/Button/Button.tsx
>      </>
Пропал тег button, фрагменты надо заменить на button.

2023-10-07 20:04 UTC, Romancikh commented on src/components/SlideBar/SlideBar.tsx
> +        })}
У map можно не делать return. Это улучшит читаемость.
```typescript
{slides.map((slide, index) => (
  <SlidePreview key={slide.id} index={index} slide={slide} />
)}
```

2023-10-11 16:04 UTC, 555Jeka555 commented on src/components/Button/Button.tsx
Я для селекта ещё не писал компоненту. Button и Select будут отдельными компонентами, я так думаю

2023-10-11 16:06 UTC, 555Jeka555 commented on src/components/SlideBar/SlideBar.tsx
> +        })}
return убирать не вариант

![image](https://github.com/Romancikh/presentation-maker/assets/75140940/fd3e41cd-cba4-441a-95c8-637f20383640)

2023-10-11 16:08 UTC, 555Jeka555 commented on src/components/SlideBar/SlideBar.tsx
> +type slideBarProps = {
Так мы типы же все с большой писали в файле types.ts

2023-10-11 16:10 UTC, 555Jeka555 commented on src/components/MenuElement/MenuElement.tsx
> +    </>
Про какие фрагменты ты говоришь?

2023-10-11 16:26 UTC, Romancikh commented on src/components/SlideBar/SlideBar.tsx
> +        })}
Видишь, я в скобки круглые завернул?

2023-10-11 16:27 UTC, Romancikh commented on src/components/SlideBar/SlideBar.tsx
> +type slideBarProps = {
Прописная - большая, строчная - маленькая.

2023-10-13 17:40 UTC, Romancikh commented on src/components/CharComponent/CharComponent.tsx
> +    color: color,
Зачем эти комментарии?

2023-10-13 17:41 UTC, Romancikh commented on src/components/Workspace/Workspace.tsx
> +  return <div key={slide.id}></div>;
key тут не нужен

2023-10-13 17:42 UTC, Romancikh commented on src/types/types.ts
> +  currentSlide: Slide;
Если мы уберём null, что ты будешь показывать, когда слайдов нет. В текущей ситуации вернётся ошибка.
![image](https://github.com/Romancikh/presentation-maker/assets/49481487/107bba99-afc9-42e7-a58d-ee5a16728b47)

2023-10-13 17:44 UTC, Romancikh commented on src/App.tsx
> +
По идее это нужно делать в Redux, поэтому пока предлагаю вынести в отдельный файл.

2023-10-13 17:45 UTC, Romancikh commented on src/App.tsx
> +
Тем более нам это сейчас не надо. В текущей реализации мы передаём готовый объект презентации.

2023-10-13 17:46 UTC, Romancikh commented on src/components/Button/Button.tsx
> +    <button className={icon ? classes.button__icon : classes.button__text}>
Если используешь БЭМ, то не нарушай.😡

2023-10-13 17:47 UTC, Romancikh commented on src/components/Header/Header.tsx
> +import classes from "./Header.module.css";
Нам точно нужны CSS модули или можно использовать обычный CSS? Просто использование БЭМ автоматически исключает повторения стилей.

2023-10-13 17:48 UTC, Romancikh commented on src/components/ToolBar/ToolBar.tsx
> +    <div className={classes.tool__bar}>
Снова нарушаешь БЭМ. 😡

2023-10-13 17:50 UTC, Romancikh commented on src/components/BodyEditor/BodyEditor.tsx
Мне не нравится название, думаю `Body` можно убрать.

2023-10-13 17:50 UTC, Romancikh commented on src/components/SlideBar/SlideBar.module.css
> +.slidebar {
Слова разделяются дефисами: `slide-bar`.

2023-10-28 07:16 UTC, Romancikh commented on src/components/common/Menu/Menu.css
> +  box-shadow: 0 0 10px rgb(0 0 0 / 10%);
#0000000a

2023-10-28 07:45 UTC, Romancikh requested changes

2023-10-28 07:45 UTC, Romancikh commented on src/components/common/Menu/Menu.tsx
> +          key={index}
Не используй index как key.

2023-10-28 07:45 UTC, Romancikh commented on src/components/common/MenuBar/MenuBar.tsx
Константы лучше вывести в отдельный файл.

2023-10-28 07:45 UTC, Romancikh commented on src/components/Workspace/Workspace.tsx
> +        <Slide key={slide.id} slide={slide} className="workspace__slide" />
Тут id не нужен

2023-10-28 07:45 UTC, Romancikh commented on src/components/Slide/Slide.tsx
> +
Лучше создать класс и уже его добавлять по условию.

2023-10-28 07:45 UTC, Romancikh commented on src/components/common/MenuBar/MenuBar.tsx
> +  namePresentation: string;
presentationName

2023-10-28 07:45 UTC, Romancikh commented on src/components/Slide/Slide.tsx
> +  isCurrentSlide: boolean;
По логике, надо изменить на isSelectedSlide.

2023-10-28 07:45 UTC, Romancikh commented on src/components/Slide/Slide.tsx
> +
Лучше вынести в отдельный класс и уже его по условию применять.

2023-10-28 08:13 UTC, Romancikh approved these changes

2023-10-28 08:14 UTC, merged